CREATE TABLE `tbprb` (
                             `start_time` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                             `enodeb_name` varchar(255) DEFAULT NULL,
                             `sector_description` varchar(255) DEFAULT NULL,
                             `sector_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                             `prb0` int DEFAULT NULL,
                             `prb1` int DEFAULT NULL,
                             `prb2` int DEFAULT NULL,
                             `prb3` int DEFAULT NULL,
                             `prb4` int DEFAULT NULL,
                             `prb5` int DEFAULT NULL,
                             `prb6` int DEFAULT NULL,
                             `prb7` int DEFAULT NULL,
                             `prb8` int DEFAULT NULL,
                             `prb9` int DEFAULT NULL,
                             `prb10` int DEFAULT NULL,
                             `prb11` int DEFAULT NULL,
                             `prb12` int DEFAULT NULL,
                             `prb13` int DEFAULT NULL,
                             `prb14` int DEFAULT NULL,
                             `prb15` int DEFAULT NULL,
                             `prb16` int DEFAULT NULL,
                             `prb17` int DEFAULT NULL,
                             `prb18` int DEFAULT NULL,
                             `prb19` int DEFAULT NULL,
                             `prb20` int DEFAULT NULL,
                             `prb21` int DEFAULT NULL,
                             `prb22` int DEFAULT NULL,
                             `prb23` int DEFAULT NULL,
                             `prb24` int DEFAULT NULL,
                             `prb25` int DEFAULT NULL,
                             `prb26` int DEFAULT NULL,
                             `prb27` int DEFAULT NULL,
                             `prb28` int DEFAULT NULL,
                             `prb29` int DEFAULT NULL,
                             `prb30` int DEFAULT NULL,
                             `prb31` int DEFAULT NULL,
                             `prb32` int DEFAULT NULL,
                             `prb33` int DEFAULT NULL,
                             `prb34` int DEFAULT NULL,
                             `prb35` int DEFAULT NULL,
                             `prb36` int DEFAULT NULL,
                             `prb37` int DEFAULT NULL,
                             `prb38` int DEFAULT NULL,
                             `prb39` int DEFAULT NULL,
                             `prb40` int DEFAULT NULL,
                             `prb41` int DEFAULT NULL,
                             `prb42` int DEFAULT NULL,
                             `prb43` int DEFAULT NULL,
                             `prb44` int DEFAULT NULL,
                             `prb45` int DEFAULT NULL,
                             `prb46` int DEFAULT NULL,
                             `prb47` int DEFAULT NULL,
                             `prb48` int DEFAULT NULL,
                             `prb49` int DEFAULT NULL,
                             `prb50` int DEFAULT NULL,
                             `prb51` int DEFAULT NULL,
                             `prb52` int DEFAULT NULL,
                             `prb53` int DEFAULT NULL,
                             `prb54` int DEFAULT NULL,
                             `prb55` int DEFAULT NULL,
                             `prb56` int DEFAULT NULL,
                             `prb57` int DEFAULT NULL,
                             `prb58` int DEFAULT NULL,
                             `prb59` int DEFAULT NULL,
                             `prb60` int DEFAULT NULL,
                             `prb61` int DEFAULT NULL,
                             `prb62` int DEFAULT NULL,
                             `prb63` int DEFAULT NULL,
                             `prb64` int DEFAULT NULL,
                             `prb65` int DEFAULT NULL,
                             `prb66` int DEFAULT NULL,
                             `prb67` int DEFAULT NULL,
                             `prb68` int DEFAULT NULL,
                             `prb69` int DEFAULT NULL,
                             `prb70` int DEFAULT NULL,
                             `prb71` int DEFAULT NULL,
                             `prb72` int DEFAULT NULL,
                             `prb73` int DEFAULT NULL,
                             `prb74` int DEFAULT NULL,
                             `prb75` int DEFAULT NULL,
                             `prb76` int DEFAULT NULL,
                             `prb77` int DEFAULT NULL,
                             `prb78` int DEFAULT NULL,
                             `prb79` int DEFAULT NULL,
                             `prb80` int DEFAULT NULL,
                             `prb81` int DEFAULT NULL,
                             `prb82` int DEFAULT NULL,
                             `prb83` int DEFAULT NULL,
                             `prb84` int DEFAULT NULL,
                             `prb85` int DEFAULT NULL,
                             `prb86` int DEFAULT NULL,
                             `prb87` int DEFAULT NULL,
                             `prb88` int DEFAULT NULL,
                             `prb89` int DEFAULT NULL,
                             `prb90` int DEFAULT NULL,
                             `prb91` int DEFAULT NULL,
                             `prb92` int DEFAULT NULL,
                             `prb93` int DEFAULT NULL,
                             `prb94` int DEFAULT NULL,
                             `prb95` int DEFAULT NULL,
                             `prb96` int DEFAULT NULL,
                             `prb97` int DEFAULT NULL,
                             `prb98` int DEFAULT NULL,
                             `prb99` int DEFAULT NULL,
                             PRIMARY KEY (`sector_name`,`start_time`),
                             KEY `tbprb_enodeb_name_index` (`enodeb_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

create definer = root@localhost trigger tbprb_format_start_time
    before insert
    on tbprb
    for each row
begin
    if instr(new.start_time, '/') = 3 then
        set @year = substr(new.start_time, 7, 4);
        set @month = left(new.start_time, 2);
        set @day = substr(new.start_time, 4, 2);
        set new.start_time = concat(@year, '-', @month, '-', @day, right(new.start_time, 9));
    end if;
end;

load data infile 'D:/tbprb.csv' ignore into table lte.tbprb
    fields terminated by ',' optionally enclosed by '"'
    lines terminated by '\r\n'
    ignore 1 lines
